apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: n9oh-project
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: N9OH Project
  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - '*'
  sourceNamespaces:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
