apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.1/manifests/install.yaml
- https://github.com/cert-manager/cert-manager/releases/download/v1.12.0/cert-manager.yaml

#patches:
# https://raw.githubusercontent.com/argoproj/argo-cd/v2.6.3/notifications_catalog/install.yaml
#- path: argocd-notifications-cm.yaml
