apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sjwoodr/argocd-config
    targetRevision: main
    path: kustomize/istio-overlay
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  ignoreDifferences:
    - group: core/v1
      kind: Secret
      name: argocd-secret
      namespace: argocd
      jsonPointers:
        - /data
