apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: n9oh-issuer
  namespace: istio-system
spec:
  acme:
    email: foo@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: n9oh-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
